/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.crio.starter;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.web.servlet.config.annotation.CorsRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;


@SpringBootApplication
// @EnableSwagger2
public class App {

  public static void main(String[] args) {
    SpringApplication.run(App.class, args);
  }

  @Bean
  public WebMvcConfigurer corsConfigurer() {
      return new WebMvcConfigurer() {
          @Override
          public void addCorsMappings(CorsRegistry registry) {
              registry.addMapping("/memes/**")
                      .allowedOrigins("*")
                      .allowedMethods("GET", "POST", "PATCH", "DELETE")
                      .allowedHeaders("*");
          }
      };
  }

}
